/*---------------------------------------------------------------------------------------------
* Copyright (c) Bentley Systems, Incorporated. All rights reserved.
* See LICENSE.md in the project root for license terms and full copyright notice.
*--------------------------------------------------------------------------------------------*/
// tslint:disable
/**
 * Reporting
 * Reporting is a resource for aggregating iTwin data to build custom dashboards and integrate iTwin data with your business applications.    - Create digitial twin based reports which can be consumed through business intelligence applications such as Power BI.  - Leverage the OData feed Data Access to generate reports by combining data from multiple data streams in the digital twin.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./clients/ReportsClient";
export * from "./interfaces/CalculatedProperties";
export * from "./interfaces/CustomCalculations";
export * from "./clients/MappingsClient";
export * from "./interfaces/Errors";
export * from "./interfaces/ExtractionProcess";
export * from "./clients/ExtractionClient";
export * from "./interfaces/GroupProperties";
export * from "./interfaces/Groups";
export * from "./interfaces/Links";
export * from "./interfaces/Mappings";
export * from "./interfaces/OData";
export * from "./clients/ODataClient";
export * from "./interfaces/Reports";
